## configuration file

site_name: XL Learn User Guide ## this is the website website name
nav:
  - Home: index.md
  - About: about.md

## curl 'https://jaspervdj.be/lorem-markdownum/markdown.txt' > docs/about.md
